repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# -   repo: https://github.com/pycqa/flake8
#     rev: 6.0.0
#     hooks:
#     -   id: flake8
#         args: [--max-line-length=100]

-   repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: bash scripts/run_ci_locally.sh
        language: system
        pass_filenames: false
        always_run: true
